### ISSUE TITLE
SplitPDF erzeugt Duplikate

### ISSUE THREAD

**Issue by sebastianpabel** [lutz/citavi-addons#4]
Hi, Daniel

Ein Kunde im Citavi-Forum berichtet, dass das Add-On Duplikate erzeugt, wenn man neue Beiträge hinzufügt: 
"Split Pdf Addon is creating duplicates if a new contribution is added after addon has run. Any fix for this?" 
-> https://help.citavi.com/en/topic/split-pdf

Viele Grüße
Sebastian

**Comment by mafsi** [comment]
Hi, Daniel
I see that you marked this topic as "not reproducible", but the problem persists. Let me explain in detail what I meant in Citavi forum.

1. I have a parent reference
2. I add a child reference {Child reference 1}
3. I use Split PDF to generate a pdf for the child reference. All is ok. Pdf is generated for Child reference 1
4. I add another child reference (Child reference 2)
5. I use split PDF to generate the file for the Child reference 2. All is ok. Pdf file for Child reference 2 is generated **but also another PDF for Child reference 1. So when I look to Child Reference 1 i have: Child_reference1_name.pdf AND Child_reference1_name (2).pdf.**
The idea is not to have again pdf generated for Child References that already have pdf.
Thanks

PS: And maybe you can modify the pdf split window to make it bigger (not via magnifier) in order to see more clear the pdf.

Thanks again for your work. Is an amazing tool!

**Comment by lutz** [comment]
@mafsi: Thank you for the message and the details about the problem. I will take a look at it, but at the moment I can't give a time frame when I will have fixed it.

**Comment by lutz** [comment]
@mafsi Today I updated the code. Now you can select every article in the dialog by double clicking it. The add-on should work with the next version of Citavi (6.4). Maybe it should work with 6.2, but I don't have time to test it at the moment.

**Comment by mafsi** [comment]
> 
> 
> @mafsi Today I updated the code. Now you can select every article in the dialog by double clicking it. The add-on should work with the next version of **Citavi 6.4**. Maybe it should work with **6.2**, but I don't have time to test it at the moment.

Thanks a lot, Daniel! I'm using beta version 6.4. I'll start using the plugin. Keep up the amazing job!
